### ISSUE TITLE
Enderbuncles won't stop spawning, ignoring mob cap.

### ISSUE THREAD

**Issue by sauerkrau5** [Lyrellion/Ars-Fauna#1]
I went to fight the ender dragon. Thousands of enderbuncles spawned in the area.

**Comment by Lyrellion** [comment]
Will look into it this evening when I get home from work.  They should be following standard mob cap rules.

On Aug 15, 2024, at 12:20 PM, sauerkrau5 ***@***.***> wrote:

﻿

I went to fight the ender dragon. Thousands of enderbuncles spawned in the area.

**Comment by Lyrellion** [comment]
I checked the code and everything seems in order.  I also loaded up my test world and spent some time in the end trying to duplicate the incident, but was unable to.  Are you using any other mods that might be removing mob caps in the end - particularly the passive creature cap?

**Comment by sauerkrau5** [comment]
It's probably something in the pack. Thanks for checking.
